### ISSUE TITLE
Update for oauth2-client v1.0

### ISSUE THREAD

**Issue by shadowhand** [DeviantArt/oauth2-deviantart#1]
Version 1.0 of the oauth2-client [has been released](https://github.com/thephpleague/oauth2-client/commit/cd64ef49e6b44660fed5c25efb2b22556deb787d) and has a relatively different API. Probably worth creating a new version of this package for those that want to use 1.0.

**Comment by muteor** [comment]
Thanks, have updated and pushed a new version.
